/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 demon.gltf --transform 
Files: demon.gltf [320.86KB] > D:\Daniel\Programming projects\React Three Fiber - Scary Challange Game\r3f-rapier-scarycg\public\models\demon-transformed.glb [54.01KB] (83%)
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

function Demon(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("./models/demon-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Attack"].play();
    actions["Attack"].timeScale = 0.05;
    actions["Walk"].play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <primitive object={nodes.Root} />
        <skinnedMesh
          name="Demon"
          geometry={nodes.Demon.geometry}
          material={materials.Atlas}
          skeleton={nodes.Demon.skeleton}
          castShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/demon-transformed.glb");

export default Demon;
