/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 flashlightmodel.glb --transform 
Files: flashlightmodel.glb [256.77KB] > D:\Daniel\Programming projects\React Three Fiber Yarn 363 Node 1817 Scary Challange Game\scarycg-yarn363-node1817\public\models\flashlightmodel-transformed.glb [16.6KB] (94%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useRef } from "react";
import { useFrame } from "@react-three/fiber";

function FlashlightModel(props) {
  let lightRef = props.lightRef;
  const { nodes, materials } = useGLTF(
    "./models/flashlightmodel-transformed.glb",
  );
  const groupRef = useRef();

  //const targetRef = useRef(new Vector3()); // Create a ref for the spotlight target

  useFrame(() => {
    if (lightRef.current && groupRef.current) {
      groupRef.current.lookAt(lightRef.current.target.position);
    }
  });
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.Flashlight_primitive0.geometry}
        material={materials.Default}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Flashlight_primitive1.geometry}
        material={materials["Mat.2"]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.Flashlight_primitive2.geometry}
        material={materials.Mat}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
    </group>
  );
}

useGLTF.preload("./models/flashlightmodel-transformed.glb");

export default FlashlightModel;
