/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Halloweenworld.glb --s --T 
Files: Halloweenworld.glb [1.18MB] > D:\Daniel\Programming projects\3D Models and textures\GLTF Blender Export\Halloweenworld-transformed.glb [572.42KB] (51%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function Halloweenworld(props) {
  const { nodes, materials } = useGLTF(
    "./models/Halloweenworld-transformed.glb",
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pumpkin001.geometry}
        material={materials.PaletteMaterial001}
        position={[2.883, 0.16, 19.41]}
        rotation={[0, 0, 0.275]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Spider_web001.geometry}
        material={materials["None.001"]}
        position={[-2.657, 5.821, -11.945]}
        rotation={[0, 0, -0.336]}
        scale={1.858}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mountain.geometry}
        material={materials["Scene textures"]}
        position={[0, 0, 3.056]}
      />
    </group>
  );
}

useGLTF.preload("./models/Halloweenworld-transformed.glb");

export default Halloweenworld;
