/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 .\quit136comp.glb --transform 
Files: .\quit136comp.glb [1.09MB] > D:\Daniel\Programming projects\React Three Fiber - Scary Challange Game\r3f-rapier-scarycg\public\models\quit136comp-transformed.glb [354.13KB] (67%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

function MapModel(props) {
  const { nodes, materials } = useGLTF("./models/quit136comp-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mountain.geometry}
        material={materials["Scene textures"]}
        position={[0, 0, 3.056]}
      />
      <instancedMesh
        args={[nodes.Grass.geometry, materials["Scene textures"], 14]}
        instanceMatrix={nodes.Grass.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.Grass010.geometry, materials["Scene textures"], 9]}
        instanceMatrix={nodes.Grass010.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("./models/quit136comp-transformed.glb");

export default MapModel;
