/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Skeleton20.glb 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useEffect } from "react";

function Skeleton20(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("./models/Skeleton20.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["Attack"].play();
    actions["Attack"].timeScale = 0.05;
    actions["Walk"].play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <primitive object={nodes.Root} />
        <skinnedMesh
          name="Skeleton"
          geometry={nodes.Skeleton.geometry}
          material={materials.Atlas}
          skeleton={nodes.Skeleton.skeleton}
          castShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload("/Skeleton20.glb");

export default Skeleton20;
