/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Spider.glb -T 
Files: Spider.glb [291.31KB] > D:\Daniel\Programming projects\3D Models and textures\GLTF Blender Export\Spider-transformed.glb [187.63KB] (36%)
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
import { useEffect } from "react";

export function Spider(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("./models/spider-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions["Spider_Walk"].play();
    actions["Spider_Walk"].timeScale = props.timeScale ? props.timeScale : 1;
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="SpiderArmature">
          <primitive object={nodes.Root} />
        </group>
        <group name="Cube">
          <skinnedMesh
            name="Cube_1"
            geometry={nodes.Cube_1.geometry}
            material={materials.Material}
            skeleton={nodes.Cube_1.skeleton}
          />
          <skinnedMesh
            name="Cube_2"
            geometry={nodes.Cube_2.geometry}
            material={materials["Material.001"]}
            skeleton={nodes.Cube_2.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("./models/spider-transformed.glb");
