/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 zombie.glb --transform 
Files: zombie.glb [238.62KB] > D:\Daniel\Programming projects\React Three Fiber - Scary Challange Game\r3f-rapier-scarycg\public\models\zombie-transformed.glb [43.43KB] (82%)
*/

/*
auto-generated by: https://github.com/pmdrs/gltfjsx
author: Quaternius (https://quaternius.com/)
license: CC0 (https://creativecommons.org/publicdomain/zero/1.0/)
source: https://quaternius.com/packs/cubeworldkit.html
title: Zombie
*/

import { useEffect, useMemo, useRef } from "react";
import { useFrame, useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

function Zombieprespos(props) {
  const group = useRef();
  const { scene, animations } = useGLTF(
    "./models/Zombiepresentationposition01.glb"
  );
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <primitive object={nodes.Root} />
        <skinnedMesh
          name="Cube000"
          geometry={nodes.Cube000.geometry}
          material={materials.Atlas}
          skeleton={nodes.Cube000.skeleton}
          castShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/Zombiepresentationposition01.glb");

export default Zombieprespos;
